import { Roboto_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/shared/Navbar/Navbar';

const robotoMono = Roboto_Mono({
  weight: ['400', "500", "700"],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark">
      <body className={robotoMono.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
